/*
 * Luis GOnzalez
 * The purpose of this project is to create an attendence app to plot data and input rosters
 */
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.*;

/**
 *
 * @author user
 */
public class CSEFinalProj extends JFrame implements ActionListener {

    RosterReader rosterReader = new RosterReader();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    public CSEFinalProj() {

        jMenuBar1 = new JMenuBar();
        jMenu1File = new JMenu();
        jMenuItem2 = new JMenuItem();
        jMenuItem1 = new JMenuItem();
        jMenuItem3 = new JMenuItem();
        jMenuItem4 = new JMenuItem();
        jMenu1 = new JMenu();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("CSE360 Final Project");
        setBackground(new Color(204, 204, 204));
        setMinimumSize(new Dimension(400, 300));
        setPreferredSize(new Dimension(900, 700));
        getContentPane().setLayout(null);

        jMenuBar1.setBorder(BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jMenu1File.setBorder(BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu1File.setText("File");
        jMenu1File.setFont(new Font("Times New Roman", 0, 36)); // NOI18N
        jMenu1File.addActionListener(this);

        jMenuItem2.setText("Load a Roster");
        jMenu1File.add(jMenuItem2);

        jMenuItem1.setText("Add Attendance");
        jMenu1File.add(jMenuItem1);

        jMenuItem3.setText("Save");
        jMenu1File.add(jMenuItem3);

        jMenuItem4.setText("Plot Data");
        jMenu1File.add(jMenuItem4);

        jMenuBar1.add(jMenu1File);

        jMenu1.setBorder(BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, Color.darkGray, Color.darkGray, Color.gray, Color.darkGray));
        jMenu1.setText("About");
        jMenu1.setFont(new Font("Times New Roman", 0, 36)); // NOI18N
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);



        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CSEFinalProj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CSEFinalProj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CSEFinalProj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CSEFinalProj.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CSEFinalProj().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public JMenu jMenu1;
    public JMenu jMenu1File;
    public JMenuBar jMenuBar1;
    public JMenuItem jMenuItem1;
    public JMenuItem jMenuItem2;
    public JMenuItem jMenuItem3;
    public JMenuItem jMenuItem4;

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() == jMenu1File){
            System.out.println("test");
            rosterReader.openFile();
        }

    }
    // End of variables declaration//GEN-END:variables
}


